language: python
python:
  - "3.6"
  - "3.7-dev"

install:
  - pip install -r requirements.txt
  - pip install codecov && codecov -t b48158bd-5b0a-4b5b-bbd4-c4bb58714f39

script:
  - pytest # or py.test for Python versions 3.5 and below

matrix:
  allow_failures:
    - python: "3.7-dev"