language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install nose
  - pip install codecov

script:
  - nosetests --with-coverage

after_success:
  - codecov