language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  - pytest # or py.test for Python versions 3.5 and below

after_success:
  - codecov -t b48158bd-5b0a-4b5b-bbd4-c4bb58714f39